language: python
sudo: enabled

cache: pip

services:
  - mysql

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - mysql -u root -h 127.0.0.1 -e 'CREATE DATABASE budgettest; CREATE DATABASE budgettest27; CREATE DATABASE budgettest36; CREATE DATABASE alembicLeft; CREATE DATABASE alembicRight;'

env:
  global:
    - SETTINGS_MODULE=biweeklybudget.tests.fixtures.test_settings
    - secure: "unGeawllwXvQdk1vT3kX09yrOh6as3K+4tOurIAlFA8K3osEAurs35fDMptFb4XYl/1eK05UAYzhvtMmdbjflxAfZCuwGH457LSOkm2/YcuaLI7tMzeu0tWSuOMco6nJyZCvsL1Bx2tyuQqI43uzHp5HcgQBSuVwb+wdfKR5m21oQTrWfVr11hZ6YiYzKLlyEQ3l5mXbbTPbrNPZF+MBR5u1qjn6QNcQgMk4e+1QvMXqjF/OIJfV7f2TzmsHmJvGIT9AR5ia9UKeR3pXoFScHUZVdlJBieAPYhS+cmq5s0N015xWwi8jhafenmA8jFSsw1aM4poot4dZzn42L+ItL5weyZZNkpCUIfkvwEKHfBgU8T/Pc7oQDd9U3aA/oO1M0M2Hc56AA1ic0iH9MLq2CUIAghUcXt2RkmgUmOv93HJJGQACdYEwIumWl7OWrlE8/mi56JoKgCPyWYUp4vTCcTH3fHmky4UVhVuO1l4hxotUl2xYsJ1Ugg50U2/ZBRKQ3lcpLXd+Oe12EC30KfhJ6rfO+LQDaIL1sFwfiSTsSf4LtljKiRGp4eLfLBQ5O8KhOIBQZoiP1iFHZWFWUjDIR9UZUib39A1lprcHVlCku9bD1PbMf51cET6UCsf1m7B7Qaq7sEMsGY71fFGq1UUwcursi8PNJmvmbKh+SvHjNVE="
    - secure: "sUpWjFDwysYIkjFyIg7XanJwlZV/y9+XvoAfWa0Q14zj1L+I2/t714P3RnB9+z8Ur7Y3ZP5gzVo0kIBeq+9yXJMd1noUUxAKYQ+KoLvN3ojyBG7Ezf/oMv7OIeqKq7GXaZUND54/lrN4FCS8YXTzgjiyA0GiCsB6Qfo51KJscObK4UOcKP6dJVnovEXPlvqWj8mnSfVZ7rKMIDNqP9O2cPQ/QLxQjCILT3461zZaklg6+xek/8npvzEaOrgHd6AiERB7je1nGBsnkvJq28kBEoCjeCVJuP2BW1a/ToutixnxO2YjJSjyAFsh5JOlb3l/Pu2KqSzXPv807cbqK5SNyAXD9GEroVOf66yZXraMnVu19H1BAi7hgMhOyPMj49tXtQr51lu4cUtwlBc3NBun0fYatd0ZdDD9rLZ+DWGmkOMzZQW7b9T5+dwFM79LzdqZqpOXcSdYC/vbXkwc2MXu04dO2e2RLgK7O4HUpgbi69Oe9AzXsU5vXwxGEGDiPaovIBaSYhxi/pgwJgsjB+HNQeuiRfYrCr9gbS75zg03GfRD75AXlCzm2S17u0VMqVXSELhUiCd3YnwCbP5ZR/nJahpW/c8Kca2Z7bfRECEctkIrpWg2oSDX5TQryD6nVMfzgYdnw6RErJN4vC0Ykk1ltiVwGEyKJPKpOifXVABt0Vo="

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37 DB_CONNSTRING='mysql+pymysql://root@127.0.0.1:3306/budgettest?charset=utf8mb4'
      dist: xenial  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: "3.9"
      env: TOXENV=py39 DB_CONNSTRING='mysql+pymysql://root@127.0.0.1:3306/budgettest?charset=utf8mb4'
    - python: "3.9"
      env: TOXENV=acceptance39 DB_CONNSTRING='mysql+pymysql://root@127.0.0.1:3306/budgettest36?charset=utf8mb4'
      dist: xenial  # required for Python 3.8 (travis-ci/travis-ci#9069)
    - python: "3.9"
      env: TOXENV=migrations MYSQL_USER='root' MYSQL_HOST='127.0.0.1' MYSQL_DBNAME_LEFT='alembicLeft' MYSQL_DBNAME_RIGHT='alembicRight' DB_CONNSTRING='mysql+pymysql://root@127.0.0.1:3306/alembicLeft?charset=utf8mb4'
      dist: xenial  # required for Python 3.8 (travis-ci/travis-ci#9069)
    - python: "3.9"
      env: TOXENV=docs
      dist: xenial  # required for Python 3.8 (travis-ci/travis-ci#9069)

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox codecov boto3
- pip freeze
- virtualenv --version
- wget -N http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- chmod +x ~/chromedriver
- cp ~/chromedriver ~/bin/

script:
  - tox -r

after_success:
  - codecov
  - ./testresults2s3.py

after_failure:
  - ./testresults2s3.py

notifications:
  email:
    on_failure: always
  pushover:
    users:
    - secure: "YNXj3CkaFff3iRPRFIilCRIacCA388Kj2AWXz6YCg8uQ7cqygNG/Lp3Vdcebth4i189unLfR95LHM2iLvN+jfXd5aHuqxtpFTtVGSy2/Y91AudkVdzI5iMZbZh/x676OoaHSShl3qREkcLMWQZYXUQitBHaIquDQsvFvHVxQHYMzLTMQ8B/DQHa2dfSBkfIO9umQwf+I/tXj+XkZCDQ6PMS9pZPTCe7jnHpfiks7KE4ukaaRpB+tNYFb9Zyht0x/DrmSrh1A9oy8MNZrsHejnWaIZ9gNEQ22WbbmSOPz4xihS4s5zf5KczVPMFaUlkFqu7uCZHJ5znmkd9wKYm/+X9pqhiGg4JuckAqEitps+9asy829nBZgWwxK2YRNG9XuAsreTZjbBsrjrOAD/I1t+/rhCU10NX9pFaNH4tYYkRQXkI5ASHcrUD0zkmlbg6sXiOSb9A6UvMverCWiK7iCcSPL31k9fMDqaxxc7kxDJlRCniuoqvXSh7ICva9ArtHa3Ouag2B2kMZ17OABRDRDvRwaAcYoCdSULyDFCsujUivTfecq5VtBau/XZAwnYqi7NmO76TizcWSbDhDxrzQNOoUMjFn7Y8U9xm3ua/fMbY3XEA6APXbbxp9+51UKujmihVhkzZwv8nljAXNYiBC6RkcWOiiHpCW9n4ANusNDSYs="
    api_key:
      secure: "on1S1hje1M8+NvqZhSROGDuTuyreIB6+CftAgOEpd8NZW+7DX66+1HdtQ7zfOe1TbYK3tYv/CFipm7UIaW84nKBXhUNy/YOvzHjAT7TgpqR3YpN7u/4fCqLWFiGp2Uyi8u+WQtcv4VKFfSyXD6J7Fk+5JyzczrV++Vlp2kgnkQ2ZfXU0lU3AyGCdnGvt9rLn4comuLuVOEyKllS12i9MUzLgF4cItOVHtwPysHmdYd+nylT0wUatbUL2f4Kb94vrjtgRqBEdCq8XUhMDjbzQ9JEdn/FgnigWswFBOOjm//2DZSTjltl0L6MzLkSSEXaTOFn63X+n0hWzA01WrIZf6mTjUTtqHUo8a2vHhBjOZRA5U+R83GXaOBNqbBGNoLGSBmUZJiz0l7gTGoy4MF+jzh8LmItau81cBDuY/l+QW3AkpsriGjO1dw0cyiEIaWI7FHYt7mesCkLQ1A7mQgsH+TiDZSDYYy5QfDY7e9PPbY5ABaGOr+Izdryy3Zdh4adjhFqBSG4wXi9m/a+P/DzPNXTXX7meZoSwPy7El/yPUsVpTjbB2iOGKvgM7MM8z/QeD/0sTDQ4ZbXDUk3Swwq9jRj712BBWj7UiEcoPoClEMxEvRQuzlcFPS8BstHwElMWne6m40yjD845fXs0DS0zxGps2o1USCdArew4LrCiFm0="
branches:
  except:
    - "/^noci-.*$/"
