"""add plaid account id, name, mask to Account

Revision ID: 5709a5bb198e
Revises: ac93b5c826a5
Create Date: 2020-03-02 05:45:05.640494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5709a5bb198e'
down_revision = 'ac93b5c826a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'accounts',
        sa.Column('plaid_account_id', sa.String(length=70), nullable=True)
    )
    op.add_column(
        'accounts',
        sa.Column('plaid_account_mask', sa.String(length=70), nullable=True)
    )
    op.add_column(
        'accounts',
        sa.Column('plaid_account_name', sa.String(length=70), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'plaid_account_name')
    op.drop_column('accounts', 'plaid_account_mask')
    op.drop_column('accounts', 'plaid_account_id')
    # ### end Alembic commands ###
