"""PlaidAccount and PlaidItem models

Revision ID: d6ae8174c86c
Revises: 073142f641b3
Create Date: 2020-03-02 20:01:42.511556

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = 'd6ae8174c86c'
down_revision = '073142f641b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('item_id', sa.String(length=70), nullable=False),
    sa.Column('token', sa.String(length=70), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_plaid_items')),
    mysql_engine='InnoDB'
    )
    op.create_table('plaid_accounts',
    sa.Column('plaid_id', sa.String(length=70), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=70), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('mask', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_plaid_accounts_account_id_accounts')),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.item_id'], name=op.f('fk_plaid_accounts_plaid_item_id_plaid_items')),
    sa.PrimaryKeyConstraint('plaid_id', 'plaid_item_id', name=op.f('pk_plaid_accounts')),
    sa.UniqueConstraint('account_id', name=op.f('uq_plaid_accounts_account_id')),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_plaid_items_name'), 'plaid_items', ['name'], unique=True)
    op.add_column('accounts', sa.Column('plaid_account_id', sa.String(length=70), nullable=True))
    op.add_column('accounts', sa.Column('plaid_item_id', sa.String(length=70), nullable=True))
    op.create_foreign_key(op.f('fk_accounts_plaid_item_id_plaid_accounts'), 'accounts', 'plaid_accounts', ['plaid_item_id', 'plaid_account_id'], ['plaid_item_id', 'plaid_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_accounts_plaid_item_id_plaid_accounts'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'plaid_item_id')
    op.drop_column('accounts', 'plaid_account_id')
    op.drop_index(op.f('ix_plaid_items_name'), table_name='plaid_items')
    op.drop_table('plaid_accounts')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
