"""PlaidAccount model

Revision ID: dfa3f6a5e10c
Revises: 48658aaee0b5
Create Date: 2020-03-02 17:55:10.656763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utc.sqltypes import UtcDateTime


# revision identifiers, used by Alembic.
revision = 'dfa3f6a5e10c'
down_revision = '48658aaee0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_accounts',
    sa.Column('plaid_id', sa.String(length=70), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=70), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('mask', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
        ['account_id'],
        ['accounts.id'],
        name=op.f('fk_plaid_accounts_account_id_accounts')
    ),
    sa.ForeignKeyConstraint(
        ['plaid_item_id'],
        ['plaid_items.item_id'],
        name=op.f('fk_plaid_accounts_plaid_item_id_plaid_items')
    ),
    sa.PrimaryKeyConstraint(
        'plaid_id', 'plaid_item_id', name=op.f('pk_plaid_accounts')
    ),
    sa.UniqueConstraint(
        'account_id', name=op.f('uq_plaid_accounts_account_id')
    ),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_accounts')
    # ### end Alembic commands ###
